### PR TITLE
bash completion

### PR DESCRIPTION
**Pull request by at-grandpa**

### CODE REVIEW

**Comment by renich** [comment]
I hope this one lands one of these days...

**Comment by at-grandpa** [comment]
Sorry. One moment, please.

**Comment by at-grandpa** [comment]
@renich 
Hi. The version 0.14.0 released a while ago added support for bash completion.
Should you have any problems, please contact me. 👍

**Comment by renich** [comment]
Dude, I appreciate all the work! Thanks a lot!

**Pull request merged**
